export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const SELECT_ACCOUNT = "SELECT_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
