export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const MERGE_TRANSACTIONS = 'MERGE_TRANSACTIONS';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
